feat: добавление возможности записи и чтения списка задач
AnastasiA-Konovalova/java-kanban pull request #2
Opened 2024-10-04 01:08 UTC by AnastasiA-Konovalova

2024-10-04 22:02 UTC, NikolaiDem requested changes

2024-10-04 22:02 UTC, NikolaiDem commented on src/save/FileBackedTaskManager.java
> +        List<String> allTasks = new ArrayList<>();
Не используется

2024-10-04 22:02 UTC, NikolaiDem commented on src/save/FileBackedTaskManager.java
> +    private StringBuilder appendItemsToFile(StringBuilder sb, Task item) {
Лучше так:
    private StringBuilder appendItemsToFile(Task item) {
        StringBuilder sb = new StringBuilder();
        sb.append(item.getId()).append(",")
                .append(item.getClass().getSimpleName()).append(",")
                .append(item.getName()).append(",")
                .append(item.getStatus().toString()).append(",");
        if (!item.getClass().getSimpleName().equals("Subtask")) {
            sb.append(item.getDescription()).append("\n");
        }
        return sb;
    }

2024-10-04 22:02 UTC, NikolaiDem commented on src/save/FileBackedTaskManager.java
> +            String[] split = readFile.get(i).split(",");
Можно вынести поля, например,
            int id = Integer.parseInt(split[0]);

2024-10-04 22:02 UTC, NikolaiDem commented on src/save/FileBackedTaskManager.java
> +        return task;
Нужно вернуть созданную таску.
Аналогично для эпиков и сабтасок

2024-10-04 22:02 UTC, NikolaiDem commented on src/save/FileBackedTaskManager.java
> +}
А методв обновления?

2024-10-04 22:02 UTC, NikolaiDem commented on test/FileBackedTaskManagerTest.java
> +        assertEquals(subtaskList2.size(), subtaskList2.size());
Что здесь проверяется?

2024-10-04 22:02 UTC, NikolaiDem commented on test/FileBackedTaskManagerTest.java
> +        FileBackedTaskManager taskManager1 = inMemoryTaskManager.loadFromFile(tmpFile);
FileBackedTaskManager actualFileManager = FileBackedTaskManager.loadFromFile(tmpFile);

2024-10-04 22:02 UTC, NikolaiDem commented on test/FileBackedTaskManagerTest.java
> +    public void testSaveAndLoadFile() throws IOException {
А вот странный кейс, вроде тест должен упасть, но он работает)
Упасть, потому что добавили новую таску:
        actualFileManager.createTask(new Task("NameTaskX", "DescriptionTask1"));

@Test
    public void testSaveAndLoadFile() throws IOException {
        tmpFile = File.createTempFile("data", null);
        FileBackedTaskManager inMemoryTaskManager = new FileBackedTaskManager(tmpFile.toString());
        inMemoryTaskManager.createTask(task1);
        inMemoryTaskManager.createTask(task2);
        inMemoryTaskManager.createEpic(epic1);
        inMemoryTaskManager.createEpic(epic2);
        inMemoryTaskManager.createSubtask(subtask1);
        List<Task> taskList1 = inMemoryTaskManager.getTaskList();
        List<Epic> epicList1 = inMemoryTaskManager.getEpicList();
        List<Subtask> subtaskList1 = inMemoryTaskManager.getSubtaskList();

        inMemoryTaskManager.save();

        FileBackedTaskManager actualFileManager = FileBackedTaskManager.loadFromFile(tmpFile);
        actualFileManager.createTask(new Task("NameTaskX", "DescriptionTask1"));
        List<Task> taskList2 = actualFileManager.getTaskList();
        List<Epic> epicList2 = actualFileManager.getEpicList();
        List<Subtask> subtaskList2 = actualFileManager.getSubtaskList();

        assertEquals(taskList1.size(), taskList2.size());
        assertEquals(epicList1.size(), epicList2.size());
        assertEquals(subtaskList2.size(), subtaskList2.size());

        for (int i = 0; i < taskList1.size(); i++) {
            assertEquals(taskList1.get(i), taskList2.get(i));
        }

        for (int i = 0; i < epicList1.size(); i++) {
            assertEquals(epicList1.get(i), epicList2.get(i));
        }

        for (int i = 0; i < subtaskList1.size(); i++) {
            assertEquals(subtaskList1.get(i), subtaskList2.get(i));
        }
    }

2024-10-04 22:02 UTC, NikolaiDem commented on test/FileBackedTaskManagerTest.java
> +    public void testSaveAndLoadFile() throws IOException {
Лучше добавить тесты и более атомарные:
на проверку отдельно тасок, сабтасок, сабтасок в эпике, эпиков.

2024-10-06 21:55 UTC, NikolaiDem requested changes

2024-10-06 21:55 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +    public void updateEpicStatus(Epic epic) {
private

2024-10-06 21:55 UTC, NikolaiDem commented on src/save/FileBackedTaskManager.java
> +    public void updateEpicStatus(Epic epic) {
не нужно переопределять

2024-10-06 21:55 UTC, NikolaiDem commented on src/save/FileBackedTaskManager.java
> +        Task task1 = super.createTask(task);
Вместо task1 лучше savedTask
Аналогично для эпиков и сабтасок

2024-10-06 21:55 UTC, NikolaiDem commented on test/FileBackedTaskManagerTest.java
> +        //что размер первоначального листа равен размеру скаченного, т.е. все эл-ты были загружены в файл
Комментарии лучше оставлять непосредственно в гитхабе

2024-10-06 21:55 UTC, NikolaiDem commented on test/FileBackedTaskManagerTest.java
> +        FileBackedTaskManager inMemoryTaskManager = new FileBackedTaskManager(tmpFile.toString());
Почему тип у переменной FileBackedTaskManager, а называется переменная inMemoryTaskManager?

2024-10-06 21:55 UTC, NikolaiDem commented on test/FileBackedTaskManagerTest.java
> +class FileBackedTaskManagerTest {
Нужен тест, в котором из непустого файла создается файловый менеджер, и проверяются восстановленные таски, сабтаски и эпики

2024-10-08 16:40 UTC, NikolaiDem commented on test/FileBackedTaskManagerTest.java
> +    public void testLoadTaskFromNotEmptyFile() throws IOException {
И такой тест работает, хотя не должен.

File tmpFile = File.createTempFile("data", null);
        Writer fileWriter = new FileWriter(tmpFile);
        fileWriter.write("""
                id,type,name,status,description,epic
                1,Task,Task_1,NEW,Go away
                2,Task,Task_2,IN_PROGRESS,Cook
                3,Task,Task_3,IN_PROGRESS,Read""");
        fileWriter.flush();
        FileBackedTaskManager actualFileManager = FileBackedTaskManager.loadFromFile(tmpFile);
        actualFileManager.createTask(new Task("name", "desc"));
        List<Task> taskList1 = actualFileManager.getTaskList();

        assertEquals(3, taskList1.size());
        assertEquals(1, taskList1.get(0).getId());
        assertEquals(Task.class, taskList1.get(0).getClass());
        assertEquals("Task_3", taskList1.get(2).getName());
        assertEquals(Status.IN_PROGRESS, taskList1.get(1).getStatus());
        assertEquals(Status.IN_PROGRESS, taskList1.get(2).getStatus());
        assertEquals("Cook", taskList1.get(1).getDescription());
        assertEquals("Read", taskList1.get(2).getDescription());

2024-10-09 00:43 UTC, AnastasiA-Konovalova commented on test/FileBackedTaskManagerTest.java
> +    public void testLoadTaskFromNotEmptyFile() throws IOException {
Я внесла правки по этому комментарию.
В соответствующих методах я приняла решение проверять объекты по всех их характеристикам (имя, описание и т.д.), получилось громоздко, но если бы я сделала это изначально, то тест бы упал сразу и я поняла, что есть проблема.

Также я внесла небольшие коррективы (для приведения к более симпатичному виду) во все другие тесты, но они касаются только используемых там названий.

2024-10-09 05:46 UTC, NikolaiDem approved these changes

2024-10-10 18:15 UTC, merged