Future/sprint 8 solution time and duration
AnastasiA-Konovalova/java-kanban pull request #3
Opened 2024-10-15 01:51 UTC by AnastasiA-Konovalova

2024-10-15 20:47 UTC, NikolaiDem requested changes

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/FileBackedTaskManager.java
> +            taskMap.values().stream()
stream() не нужен

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/FileBackedTaskManager.java
> +            epicMap.values().stream()
stream() не нужен

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/FileBackedTaskManager.java
> +                            throw new ManagerSaveException("Ошибка в чтении задачи формата task");
В чтении или записи?

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/FileBackedTaskManager.java
> +                            throw new ManagerSaveException("Ошибка в чтении задачи формата epic");
В чтении или записи?

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/FileBackedTaskManager.java
>              for (Subtask item : subtaskMap.values()) {
Почему не forEach?

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/FileBackedTaskManager.java
> +                    .forEach(item -> {
В функциональном стиле это может выглядеть так:

taskMap.values()
                    .forEach(ThrowableConsumer.of(item -> fileWriter.write(appendItemsToFile(item).toString()),
                            ex -> new ManagerSaveException("Ошибка в чтении задачи формата task")));

    interface ThrowableConsumer<T> {

        static <T> Consumer<T> of(ThrowableConsumer<T> wrapped, Function<Throwable, RuntimeException> throwableFunction) {
            return t -> {
                try {
                    wrapped.apply(t);
                } catch (Exception e) {
                    throw throwableFunction.apply(e);
                }
            };
        }

        void apply(T t) throws Exception;
    }

Аналогично для эпиков и сабтасок

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/FileBackedTaskManager.java
>                  StringBuilder sb = appendItemsToFile(item);
Можно сделать по аналогии с эпиками и тасками?

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/InMemoryHistoryManager.java
> +        taskManager = Managers.getDefault();
Пересечение нужно искать только внутри таск менеджера

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +            System.out.println("Создаваемая задача пересекается по времени с существующей");
Лучше бросить исключение. Аналогично для сабтасок

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +        if (!validateTask(updateTasks)) {
Не будет ли здесь обновляющая задача пересекаться с обновляемой?

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +        if (!validateTask(updateSubtask)) {
Не будет ли здесь обновляющая задача пересекаться с обновляемой?

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +    public void getEndTimeForEpic(Epic epic) {
Если метод называется get, то он не должен иметь сайд эффекта.
И может выглядеть так:
    public Instant getStartTimeForEpic(Epic epic) {
        return getSubtaskFromEpic(epic.getId())
                .stream()
                .map(Subtask::getStartTime)
                .min(Comparator.comparing(Function.identity()))
                .orElse(null);         
    }
Аналогично для расчета duration и endTime

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +    private List<Subtask> searchTimeCharacteristicsSubtask(Epic epic) {
Метод не нужен

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +    public Set<Task> getPrioritizedTasks() {
Не выполнено условие ТЗ : получение списка приоритетных задач за O(n)

2024-10-15 20:47 UTC, NikolaiDem commented on src/manager/TaskManager.java
> +    Set<Task> getPrioritizedTasks(); //убрать?
Убрать все новые методы кроме этого.
Лучше вернуть List<>

2024-10-15 20:47 UTC, NikolaiDem commented on src/tasks/Subtask.java
> +    @Override
Методы не нужны, уже есть в Task

2024-10-18 01:09 UTC, NikolaiDem requested changes

2024-10-18 01:09 UTC, NikolaiDem commented on src/manager/FileBackedTaskManager.java
> +                        StringBuilder sb = appendItemsToFile(item);
Code smells:
Метод appendItemsToFile выглядит неполноценным. Он вроде как должен преобразовать таск в строку, но делает это лишь отчасти. Лучше перенести логику в этот метод или сделать 3 отдельных метода для каждого типа задачи. Или сделать метод в таске, который вернет файловое представление таски

2024-10-18 01:09 UTC, NikolaiDem commented on src/manager/FileBackedTaskManager.java
>      public void save() {
private

2024-10-18 01:09 UTC, NikolaiDem commented on src/manager/FileBackedTaskManager.java
> +    public static void loadStartTimeAndDuration(Task task, String[] split) {
private

2024-10-18 01:09 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +            throw new RuntimeException("Создаваемая задача пересекается по времени с существующей");
Лучше сделать свое кастомное исключение с явной причиной.
Аналогично для остальных RuntimeException

2024-10-18 01:09 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +        if (!validateTask(task)) {
Если таска не прошла валидацию, то мы ее должны добавить?

2024-10-18 01:09 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +        if (subtask.getStartTime() != null) {
По ТЗ нужно в приоритетный список добавлять все задачи

2024-10-18 01:09 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +                if (oldTask.getEndTime() != null) {
Можно вынести за пределы if-else

2024-10-18 01:09 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +                if (subtask.getEndTime() != null) {
Можно вынести за пределы if-else

2024-10-18 01:09 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +//        Epic removeEpic = epicMap.remove(id);
Закомментированный код не нужен

2024-10-18 01:09 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +    public Instant getStartTimeForEpic(Epic epic) {
Все вспомогательные методы должны быть private

2024-10-18 01:09 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +    public boolean validateTask(Task taskForCheck) {
private

2024-10-18 01:09 UTC, NikolaiDem commented on src/manager/TaskManager.java
> +    void updateTask(Task task, Task updateTasks);
Менять сигнатуры метод не нужно

2024-10-19 14:44 UTC, AnastasiA-Konovalova commented on src/manager/InMemoryTaskManager.java
> +        if (subtask.getStartTime() != null) {
"Дата начала задачи по каким-то причинам может быть не задана. Тогда при добавлении её не следует учитывать в списке задач и подзадач, отсортированных по времени начала. Такая задача не влияет на приоритет других, а при попадании в список может сломать логику работы компаратора."

Это отрывок из ТЗ.  Как я понимаю он говорит о том, что задачи, у которых не указано начальное время не попадают в отсортированный список, т.к. их сортировка невозможна и может сломать логику работы.

Или в комментарии к коду имеется в виду какой-то другой момент?

2024-10-19 22:43 UTC, NikolaiDem commented on src/manager/InMemoryTaskManager.java
> +        if (subtask.getStartTime() != null) {
Там же частица "не"....((
Все правильно тогда, молодец)

2024-10-19 22:43 UTC, NikolaiDem approved these changes

2024-10-22 19:16 UTC, merged